version: 2.1

jobs:
  
  defaultBuildProductionTheme:
    docker:
      - image: node:10
    steps:
      - run:
          command: |
            yarn
            yarn lint:scripts
            yarn lint:styles
            yarn build:production

  installPHPPackages:
    docker:
      - image: php:7.2
    steps:    
      - run:
          command: |
            pwd
            ls ../
            apt-get update && apt-get install -y unzip curl libmcrypt-dev mysql-client
            docker-php-ext-install pdo_mysql
            curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            composer install --no-ansi --no-dev --no-interaction --no-progress --optimize-autoloader --no-scripts

workflows:

  default:
    jobs:
      - defaultBuildProductionTheme
      #- installPHPPackages
